runtime: php72

# Put production environment variables here.
env_variables:
  # Applicaton key
  APP_KEY: base64:uBkIxf8LzynslZzCCnUCSnmQbLUzqAnT3hCy6z2qj6s=
  # Storage path
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: pap_db
  DB_USERNAME: root
  DB_PASSWORD: 7hvwaEG7q0jxi3vt
  DB_SOCKET: "/cloudsql/pap-app-01:australia-southeast1:pap-db"

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js